name: Update GitHub Stats in README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch GitHub Stats
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&layout=compact&count_private=true&token=${{ secrets.STATS_TOKEN }}"

      - name: Update README
        run: |
          echo "![Top Langs](github-stats.svg)" > README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add README.md github-stats.svg
          git commit -m "Updated GitHub Stats"
          git push
